package pdfdocumente;

import com.itextpdf.text.Chunk;
import com.itextpdf.text.Document;
import com.itextpdf.text.DocumentException;
import com.itextpdf.text.Font;
import com.itextpdf.text.Image;
import com.itextpdf.text.PageSize;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.Phrase;
import com.itextpdf.text.Font.FontFamily;
import com.itextpdf.text.pdf.PdfWriter;
import java.io.FileOutputStream;
import java.io.IOException;
import java.sql.SQLException;
import logging.logging;
import run.runApplication;
import utilities.BildUmrechnenService;
import utilities.SbcUtils;

public class BerichtPDFSchreiben_alt {

   private static final Font UEBERSCHRIFT = new Font(FontFamily.HELVETICA, 22.0F, 1);
   private static final Font NORMAL_FONT = new Font(FontFamily.HELVETICA, 12.0F, 0);
   private static final Font NORMAL_BOLD = new Font(FontFamily.HELVETICA, 12.0F, 1);


   public void createPdf(String filename, String title, String text) throws DocumentException, IOException, SQLException {
      Document document = new Document();
      PdfWriter writer = PdfWriter.getInstance(document, new FileOutputStream(filename));
      document.open();
      Image imgBanner = Image.getInstance((String)runApplication.EINSTELLUNGEN.get("briefkopf"));
      imgBanner.scaleAbsoluteHeight((float)BildUmrechnenService.bildHoeheVerkleinernPDF(imgBanner, 500));
      imgBanner.scaleAbsoluteWidth((float)BildUmrechnenService.bildBreiteVerkleinernPDF(imgBanner, 520));
      document.add(imgBanner);
      String[] bericht = text.split("\n");
      Phrase textblock = new Phrase();
      textblock.add(Chunk.NEWLINE);
      textblock.add(Chunk.NEWLINE);
      Chunk chunk = new Chunk(title, UEBERSCHRIFT);
      textblock.add(chunk);
      textblock.add(Chunk.NEWLINE);
      textblock.add(Chunk.NEWLINE);
      chunk = new Chunk("Bericht:", NORMAL_BOLD);
      textblock.add(chunk);
      textblock.add(Chunk.NEWLINE);
      textblock.add(Chunk.NEWLINE);

      for(int jahr = 0; jahr < bericht.length; ++jahr) {
         chunk = new Chunk(bericht[jahr], NORMAL_FONT);
         textblock.add(chunk);
         textblock.add(Chunk.NEWLINE);
      }

      textblock.add(Chunk.NEWLINE);
      textblock.add(Chunk.NEWLINE);
      document.add(new Paragraph(textblock));
      document.newPage();
      String var47 = SbcUtils.timeStamp("yyyy");
      Image imgAnwesenheitEinsatz = Image.getInstance(runApplication.arbeitsverzeichnis + "data/" + var47 + "/temp/Anwesenheit_Einsatz.jpg");
      imgAnwesenheitEinsatz.scaleAbsoluteHeight((float)BildUmrechnenService.bildHoeheVerkleinernPDF(imgAnwesenheitEinsatz, 400));
      imgAnwesenheitEinsatz.scaleAbsoluteWidth((float)BildUmrechnenService.bildBreiteVerkleinernPDF(imgAnwesenheitEinsatz, 550));
      Phrase textblock2 = new Phrase();
      Chunk chunk2 = new Chunk("Anwesenheitsstatistik Einsatz:", UEBERSCHRIFT);
      textblock2.add(Chunk.NEWLINE);
      textblock2.add(chunk2);
      textblock2.add(Chunk.NEWLINE);
      textblock2.add(Chunk.NEWLINE);
      document.add(new Paragraph(textblock2));
      document.add(imgAnwesenheitEinsatz);
      Image imgAnwesenheitBSW = Image.getInstance(runApplication.arbeitsverzeichnis + "data/" + var47 + "/temp/Anwesenheit_Brandsicherheitswache.jpg");
      imgAnwesenheitBSW.scaleAbsoluteHeight((float)BildUmrechnenService.bildHoeheVerkleinernPDF(imgAnwesenheitBSW, 400));
      imgAnwesenheitBSW.scaleAbsoluteWidth((float)BildUmrechnenService.bildBreiteVerkleinernPDF(imgAnwesenheitBSW, 500));
      Phrase textblock3 = new Phrase();
      Chunk chunk3 = new Chunk("Anwesenheitsstatistik BSW:", UEBERSCHRIFT);
      textblock3.add(Chunk.NEWLINE);
      textblock3.add(chunk3);
      textblock3.add(Chunk.NEWLINE);
      textblock3.add(Chunk.NEWLINE);
      document.add(new Paragraph(textblock3));
      document.add(imgAnwesenheitBSW);
      document.newPage();
      Image imgAnwesenheitDienst = Image.getInstance(runApplication.arbeitsverzeichnis + "data/" + var47 + "/temp/Anwesenheit_Dienst.jpg");
      imgAnwesenheitDienst.scaleAbsoluteHeight((float)BildUmrechnenService.bildHoeheVerkleinernPDF(imgAnwesenheitDienst, 400));
      imgAnwesenheitDienst.scaleAbsoluteWidth((float)BildUmrechnenService.bildBreiteVerkleinernPDF(imgAnwesenheitDienst, 500));
      Phrase textblock4 = new Phrase();
      Chunk chunk4 = new Chunk("Anwesenheitsstatistik Dienst:", UEBERSCHRIFT);
      textblock4.add(Chunk.NEWLINE);
      textblock4.add(chunk4);
      textblock4.add(Chunk.NEWLINE);
      textblock4.add(Chunk.NEWLINE);
      document.add(new Paragraph(textblock4));
      document.add(imgAnwesenheitDienst);
      Image imgAnwesenheitGesamt = Image.getInstance(runApplication.arbeitsverzeichnis + "data/" + var47 + "/temp/Anwesenheit_Gesamt.jpg");
      imgAnwesenheitGesamt.scaleAbsoluteHeight((float)BildUmrechnenService.bildHoeheVerkleinernPDF(imgAnwesenheitGesamt, 400));
      imgAnwesenheitGesamt.scaleAbsoluteWidth((float)BildUmrechnenService.bildBreiteVerkleinernPDF(imgAnwesenheitGesamt, 500));
      Phrase textblock5 = new Phrase();
      Chunk chunk5 = new Chunk("Anwsenheitsstatistik Gesamt:", UEBERSCHRIFT);
      textblock5.add(Chunk.NEWLINE);
      textblock5.add(chunk5);
      textblock5.add(Chunk.NEWLINE);
      textblock5.add(Chunk.NEWLINE);
      document.add(new Paragraph(textblock5));
      document.add(imgAnwesenheitGesamt);
      document.newPage();
      Image imgAusrueckezeiten = Image.getInstance(runApplication.arbeitsverzeichnis + "data/" + var47 + "/temp/Ausrückezeit.jpg");
      imgAusrueckezeiten.scaleAbsoluteHeight((float)BildUmrechnenService.bildHoeheVerkleinernPDF(imgAusrueckezeiten, 400));
      imgAusrueckezeiten.scaleAbsoluteWidth((float)BildUmrechnenService.bildBreiteVerkleinernPDF(imgAusrueckezeiten, 500));
      Phrase textblock6 = new Phrase();
      Chunk chunk6 = new Chunk("Ausrückzeiten:", UEBERSCHRIFT);
      textblock6.add(Chunk.NEWLINE);
      textblock6.add(chunk6);
      textblock6.add(Chunk.NEWLINE);
      textblock6.add(Chunk.NEWLINE);
      document.add(new Paragraph(textblock6));
      document.add(imgAusrueckezeiten);
      Image imgEinsatzart = Image.getInstance(runApplication.arbeitsverzeichnis + "data/" + var47 + "/temp/Einsatzart.jpg");
      imgEinsatzart.scaleAbsoluteHeight((float)BildUmrechnenService.bildHoeheVerkleinernPDF(imgEinsatzart, 400));
      imgEinsatzart.scaleAbsoluteWidth((float)BildUmrechnenService.bildBreiteVerkleinernPDF(imgEinsatzart, 500));
      Phrase textblock7 = new Phrase();
      Chunk chunk7 = new Chunk("Einsatzübersicht (Einsatzart):", UEBERSCHRIFT);
      textblock7.add(Chunk.NEWLINE);
      textblock7.add(chunk7);
      textblock7.add(Chunk.NEWLINE);
      textblock7.add(Chunk.NEWLINE);
      document.add(new Paragraph(textblock7));
      document.add(imgEinsatzart);
      document.newPage();
      Image imgEinsatzMannstunden = Image.getInstance(runApplication.arbeitsverzeichnis + "data/" + var47 + "/temp/EinsatzMannstunden.jpg");
      imgEinsatzMannstunden.scaleAbsoluteHeight((float)BildUmrechnenService.bildHoeheVerkleinernPDF(imgEinsatzMannstunden, 400));
      imgEinsatzMannstunden.scaleAbsoluteWidth((float)BildUmrechnenService.bildBreiteVerkleinernPDF(imgEinsatzMannstunden, 500));
      Phrase textblock8 = new Phrase();
      Chunk chunk8 = new Chunk("Einsatzmannstunden:", UEBERSCHRIFT);
      textblock8.add(Chunk.NEWLINE);
      textblock8.add(chunk8);
      textblock8.add(Chunk.NEWLINE);
      textblock8.add(Chunk.NEWLINE);
      document.add(new Paragraph(textblock8));
      document.add(imgEinsatzMannstunden);
      Image imgBSWMannstunden = Image.getInstance(runApplication.arbeitsverzeichnis + "data/" + var47 + "/temp/BSWMannstunden.jpg");
      imgBSWMannstunden.scaleAbsoluteHeight((float)BildUmrechnenService.bildHoeheVerkleinernPDF(imgBSWMannstunden, 400));
      imgBSWMannstunden.scaleAbsoluteWidth((float)BildUmrechnenService.bildBreiteVerkleinernPDF(imgBSWMannstunden, 500));
      Phrase textblock9 = new Phrase();
      Chunk chunk9 = new Chunk("BSW Mannstunden:", UEBERSCHRIFT);
      textblock9.add(Chunk.NEWLINE);
      textblock9.add(chunk9);
      textblock9.add(Chunk.NEWLINE);
      textblock9.add(Chunk.NEWLINE);
      document.add(new Paragraph(textblock9));
      document.add(imgBSWMannstunden);
      document.newPage();
      Image imgEinsatzProMonat = Image.getInstance(runApplication.arbeitsverzeichnis + "data/" + var47 + "/temp/EinsatzProMonat.jpg");
      imgEinsatzProMonat.scaleAbsoluteHeight((float)BildUmrechnenService.bildHoeheVerkleinernPDF(imgEinsatzProMonat, 400));
      imgEinsatzProMonat.scaleAbsoluteWidth((float)BildUmrechnenService.bildBreiteVerkleinernPDF(imgEinsatzProMonat, 500));
      Phrase textblock10 = new Phrase();
      Chunk chunk10 = new Chunk("Einsatzstatistik Monat/Anzahl:", UEBERSCHRIFT);
      textblock10.add(Chunk.NEWLINE);
      textblock10.add(chunk10);
      textblock10.add(Chunk.NEWLINE);
      textblock10.add(Chunk.NEWLINE);
      document.add(new Paragraph(textblock10));
      document.add(imgEinsatzProMonat);
      Image imgEinsatzProStunde = Image.getInstance(runApplication.arbeitsverzeichnis + "data/" + var47 + "/temp/EinsatzProStunde.jpg");
      imgEinsatzProStunde.scaleAbsoluteHeight((float)BildUmrechnenService.bildHoeheVerkleinernPDF(imgEinsatzProStunde, 400));
      imgEinsatzProStunde.scaleAbsoluteWidth((float)BildUmrechnenService.bildBreiteVerkleinernPDF(imgEinsatzProStunde, 500));
      Phrase textblock11 = new Phrase();
      Chunk chunk11 = new Chunk("Einsatzstatistik Stunde/Anzahl:", UEBERSCHRIFT);
      textblock11.add(Chunk.NEWLINE);
      textblock11.add(chunk11);
      textblock11.add(Chunk.NEWLINE);
      textblock11.add(Chunk.NEWLINE);
      document.add(new Paragraph(textblock11));
      document.add(imgEinsatzProStunde);
      document.newPage();
      Image imgEinsatzProWochentag = Image.getInstance(runApplication.arbeitsverzeichnis + "data/" + var47 + "/temp/EinsatzProWochentag.jpg");
      imgEinsatzProWochentag.scaleAbsoluteHeight((float)BildUmrechnenService.bildHoeheVerkleinernPDF(imgAnwesenheitGesamt, 400));
      imgEinsatzProWochentag.scaleAbsoluteWidth((float)BildUmrechnenService.bildBreiteVerkleinernPDF(imgAnwesenheitGesamt, 500));
      Phrase textblock13 = new Phrase();
      Chunk chunk13 = new Chunk("Einsatzstatistik Wochentag/Anzahl:", UEBERSCHRIFT);
      textblock13.add(Chunk.NEWLINE);
      textblock13.add(chunk13);
      textblock13.add(Chunk.NEWLINE);
      textblock13.add(Chunk.NEWLINE);
      document.add(new Paragraph(textblock13));
      document.add(imgEinsatzProWochentag);
      Image imgAbwesenheit = Image.getInstance(runApplication.arbeitsverzeichnis + "data/" + var47 + "/temp/Abwesenheit.jpg");
      imgAbwesenheit.scaleAbsoluteHeight((float)BildUmrechnenService.bildHoeheVerkleinernPDF(imgAnwesenheitGesamt, 400));
      imgAbwesenheit.scaleAbsoluteWidth((float)BildUmrechnenService.bildBreiteVerkleinernPDF(imgAnwesenheitGesamt, 500));
      Phrase textblock12 = new Phrase();
      Chunk chunk12 = new Chunk("Abwesenheitsgründe:", UEBERSCHRIFT);
      textblock12.add(Chunk.NEWLINE);
      textblock12.add(chunk12);
      textblock12.add(Chunk.NEWLINE);
      textblock12.add(Chunk.NEWLINE);
      document.add(new Paragraph(textblock12));
      document.add(imgAbwesenheit);
      document.addTitle("FeuerwehrManagementSystem - Bericht " + var47);
      document.addAuthor("FeuerwehrManagementSystem");
      document.addCreationDate();
      document.addSubject("Bericht " + var47);
      document.close();
      writer.close();
   }

   private void printMeasures() {
      logging.logInfo("A4-Maße: " + PageSize.A4.getWidth() + "pt x " + PageSize.A4.getHeight() + "pt - " + (double)PageSize.A4.getWidth() * 0.3527D + "mm x " + (double)PageSize.A4.getHeight() * 0.3527D + "mm");
   }

   public static void PDFdocumentErstellen(String dateiname, String title, String text) throws DocumentException, IOException, SQLException {
      BerichtPDFSchreiben_alt ps = new BerichtPDFSchreiben_alt();
      ps.createPdf(dateiname, title, text);
      ps.printMeasures();
      logging.logInfo("Datensatz wurde in eine PDF Datei Exportiert");
   }
}
